<?php

namespace Wegar\Basic\Command;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Wegar\Basic\Helper\EnvHelper;
use Wegar\Basic\Trait\Command as CommandTrait;

/**
 * 扫描 config 目录，把连接/凭据类字面量迁移到 .env：
 * 默认只预演（生成/更新 .env.example），加 `--write` 才改写 config（并留 .bak）。
 */
class Env extends Command
{
  protected static string $defaultName = 'wegar:basic:env';
  protected static string $defaultDescription = '扫描 config 并把连接/凭据字面量迁移到 .env（默认预演，--write 落盘）';

  use CommandTrait;

  protected function configure(): void
  {
    $this->addOption('write', null, InputOption::VALUE_NONE, '实际改写 config 并更新 .env.example（默认只预演）');
    $this->addOption('path', null, InputOption::VALUE_REQUIRED, 'config 目录', '');
    $this->addOption('env-file', null, InputOption::VALUE_REQUIRED, '.env.example 路径', '');
    $this->addOption('exclude', null, InputOption::VALUE_REQUIRED, '要跳过的目录/文件（逗号分隔）', 'plugin');
  }

  protected function execute(InputInterface $input, OutputInterface $output): int
  {
    $this->input = $input;
    $this->output = $output;

    $path = $input->getOption('path') ?: base_path('config');
    $envFile = $input->getOption('env-file') ?: base_path('.env.example');
    $exclude = array_filter(array_map('trim', explode(',', (string)$input->getOption('exclude'))));
    $write = (bool)$input->getOption('write');

    $files = $this->configFiles($path, $exclude);
    if ($files === []) {
      $this->warning("未找到可处理的配置文件：$path");
      return self::SUCCESS;
    }

    $entries = [];
    $rewritten = 0;
    foreach ($files as $file) {
      $config = $this->loadConfig($file);
      if (!is_array($config)) {
        continue;
      }
      $candidates = EnvHelper::candidates($config, pathinfo($file, PATHINFO_FILENAME));
      if ($candidates === []) {
        continue;
      }
      $rel = substr($file, strlen(rtrim($path, '/')) + 1);
      $this->info("$rel: " . count($candidates) . ' 处候选');
      foreach ($candidates as $candidate) {
        $entries[$candidate['envKey']] = $candidate['value'];
      }
      if ($write) {
        $source = (string)file_get_contents($file);
        $result = EnvHelper::rewrite($source, $candidates);
        if ($result['changed'] > 0) {
          if (!file_exists($file . '.bak')) {
            copy($file, $file . '.bak');
          }
          file_put_contents($file, $result['source']);
          $rewritten += $result['changed'];
        }
      }
    }

    $added = $this->updateEnvExample($envFile, $entries);

    if ($write) {
      $this->success("已改写 $rewritten 处，.env.example 新增 $added 个键（原文件已备份为 *.bak）。");
    } else {
      $this->notice('预演：共 ' . count($entries) . " 个候选键，未改动任何文件；加 --write 落盘。");
    }

    return self::SUCCESS;
  }

  /**
   * @param string[] $exclude
   * @return string[]
   */
  private function configFiles(string $path, array $exclude): array
  {
    if (!is_dir($path)) {
      return [];
    }
    $base = rtrim($path, '/');
    $files = [];
    $iterator = new RecursiveIteratorIterator(
      new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS),
      RecursiveIteratorIterator::LEAVES_ONLY
    );
    /** @var SplFileInfo $file */
    foreach ($iterator as $file) {
      if (!$file->isFile() || $file->getExtension() !== 'php') {
        continue;
      }
      $rel = substr($file->getPathname(), strlen($base) + 1);
      $skip = false;
      foreach ($exclude as $segment) {
        if ($segment === '') {
          continue;
        }
        if ($rel === $segment || str_starts_with($rel, $segment . '/') || str_contains($rel, '/' . $segment . '/')) {
          $skip = true;
          break;
        }
      }
      if (!$skip) {
        $files[] = $file->getPathname();
      }
    }
    sort($files);
    return $files;
  }

  private function loadConfig(string $file): mixed
  {
    return include $file;
  }

  /**
   * @param array<string, scalar> $entries
   * @return int 新增键数
   */
  private function updateEnvExample(string $envFile, array $entries): int
  {
    ksort($entries);
    $existing = is_file($envFile) ? (string)file_get_contents($envFile) : '';
    $present = [];
    if ($existing !== '' && preg_match_all('/^\s*([A-Za-z0-9_]+)\s*=/m', $existing, $m)) {
      $present = array_flip($m[1]);
    }

    $lines = [];
    foreach ($entries as $key => $value) {
      if (!isset($present[$key])) {
        $lines[] = $key . '=' . $this->formatEnvValue($value);
      }
    }
    if ($lines === []) {
      return 0;
    }

    $block = ($existing === '' ? '' : rtrim($existing) . "\n\n")
      . "# generated by wegar:basic:env\n"
      . implode("\n", $lines) . "\n";
    $dir = dirname($envFile);
    if (!is_dir($dir)) {
      mkdir($dir, 0777, true);
    }
    file_put_contents($envFile, $block);

    return count($lines);
  }

  private function formatEnvValue(mixed $value): string
  {
    if (is_bool($value)) {
      return $value ? 'true' : 'false';
    }
    $string = (string)$value;
    return preg_match('/[\s#="\']/', $string) ? '"' . addcslashes($string, '"\\') . '"' : $string;
  }
}
